namespace KursuchServer;

public enum DBCommandType
{
    AccountGetPassword = 0,
    AccountGetAll = 1,
    AccountGetAllAsString = 2,
    AccountAdd = 3,
    AccountDelete = 4,
    AccountModify = 5,
    CheckAdminKey = 6,
    CheckAccountData = 7,
    GoodAdd,
    GoodDelete,
    GoodModify,
    GoodGet,
    GoodGetAll,
    SellerAdd,
    SellerDelete,
    SellerModify,
    SellerGet,
    SellerGetAll,
    AquireTypeAdd,
    AquireTypeDelete,
    AquireTypeGet,
    AquireTypeGetAll,
    PaymentMethodAdd,
    PaymentMethodDelete,
    PaymentMethodGet,
    PaymentMethodGetAll,
    GameAdd,
    GameDelete,
    GameGet,
    GameGetAll,
}