namespace KursuchServer;

public enum GCommandType
{
    GoodAdd,
    GoodDelete,
    GoodModify,
    GoodGet,
    GoodGetAll,
    GoodDeleteAP,
    GoodGetAllAP,
    GoodGetAllSeller,
    GoodDeleteSeller,
    GoodModifySeller,
    SellerAdd,
    SellerDelete,
    SellerModify,
    SellerGet,
    SellerGetAll,
    PaymentMethodAdd,
    PaymentMethodDelete,
    PaymentMethodGet,
    PaymentMethodGetAll,
    GameAdd,
    GameDelete,
    GameGet,
    GameGetAll,
    GameModify,
    PaymentMethodModify,
    CartAdd,
    CartItemAdd,
    CartItemDelete,
    CartItemGetAll,
    CheckOut
}